[package]
name = "minicoro-sys"
version = "0.8.0"
edition = "2021"

readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "*"